# Generated by Django 2.2.6 on 2019-10-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='approval',
            name='data',
            field=models.CharField(default=None, max_length=8000),
            preserve_default=False,
        ),
    ]
