# Generated by Django 2.2.6 on 2019-10-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191020_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='public_key',
            field=models.CharField(blank=True, max_length=2050, null=True),
        ),
    ]
