# Generated by Django 2.2.6 on 2019-10-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191020_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='previous_hash',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='approval',
            name='signature',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='public_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
