# Generated by Django 2.2.6 on 2019-10-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191021_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
